@startuml
class GraphCanvas {
    + <<const>> VertexRadius : double = 10
    +  <<event>> VertexClicked : Action<BaseVertex>? 
    +  <<event>> VertexRightClicked : Action<BaseVertex>? 
    + <<override>> Render(context:DrawingContext) : void
}
class "List`1"<T> {
}
class GraphLayout {
    + MinX : double <<get>> <<set>>
    + MinY : double <<get>> <<set>>
    + Scale : double <<get>> <<set>>
    + OffsetX : double <<get>> <<set>>
    + OffsetY : double <<get>> <<set>>
}
Control <|-- GraphCanvas
GraphCanvas o-> "Vertices<BaseVertex>" "List`1"
GraphCanvas o-> "Edges<BaseEdge>" "List`1"
GraphCanvas +-- GraphLayout
@enduml
