@startuml
!include .\\GraphVisualizer\App.axaml.puml
!include .\\GraphVisualizer\GraphCanvas.puml
!include .\\GraphVisualizer\MainWindow.axaml.puml
!include .\\GraphVisualizer\Program.puml
!include .\\Vertex\CityVertex.puml
!include .\\Vertex\Edge.puml
!include .\\Vertex\StartVertex.puml
!include .\\Vertex\Vertex.puml
!include .\\Vertex\WallVertex.puml
@enduml
